---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import Vpc Setup Variables
      include_vars: /home/ubuntu/ansible-aws-vpc/vars/bastion_setup

    - name: Import Vpc Setup Variables
      include_vars: /home/ubuntu/ansible-aws-vpc/vars/output_vars

    - name: Import acess keys Variables
      include_vars: /home/ubuntu/ansible-aws-vpc/vars/aws_key

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{ region }}"
      register: key_out

    - name: save private key into file bastion-key.pem
      copy:
        content: "{{ key_out.key.private_key }}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Security Groups for Bastion host
      ec2_group:
        name: Bastion-host-sg
        description: allow port 22 from everywhere and all port within sg
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ MYIP }}"
      register: BastionSG_out

    - name: Creating Bastion Host
      ec2:
        aws_access_key: "{{ a_key }}"
        aws_secret_key: "{{ s_key }}"
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_Host"
          Project: Vprofile
          Owner: "Devops_Teams"
        group_id: "{{ BastionSG_out.group_id }}"
        vpc_subnet_id: "{{ pubsub1id }}"
      register: bastionHost_out